import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app-settings`; params?: Router.UnknownInputParams; } | { pathname: `/game-settings`; params?: Router.UnknownInputParams; } | { pathname: `/get-started`; params?: Router.UnknownInputParams; } | { pathname: `/how-to-play`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/privacy-policy`; params?: Router.UnknownInputParams; } | { pathname: `/reveal`; params?: Router.UnknownInputParams; } | { pathname: `/share`; params?: Router.UnknownInputParams; } | { pathname: `/terms-of-use`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/app-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/game-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/get-started`; params?: Router.UnknownOutputParams; } | { pathname: `/how-to-play`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/privacy-policy`; params?: Router.UnknownOutputParams; } | { pathname: `/reveal`; params?: Router.UnknownOutputParams; } | { pathname: `/share`; params?: Router.UnknownOutputParams; } | { pathname: `/terms-of-use`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/app-settings${`?${string}` | `#${string}` | ''}` | `/game-settings${`?${string}` | `#${string}` | ''}` | `/get-started${`?${string}` | `#${string}` | ''}` | `/how-to-play${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/privacy-policy${`?${string}` | `#${string}` | ''}` | `/reveal${`?${string}` | `#${string}` | ''}` | `/share${`?${string}` | `#${string}` | ''}` | `/terms-of-use${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app-settings`; params?: Router.UnknownInputParams; } | { pathname: `/game-settings`; params?: Router.UnknownInputParams; } | { pathname: `/get-started`; params?: Router.UnknownInputParams; } | { pathname: `/how-to-play`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/privacy-policy`; params?: Router.UnknownInputParams; } | { pathname: `/reveal`; params?: Router.UnknownInputParams; } | { pathname: `/share`; params?: Router.UnknownInputParams; } | { pathname: `/terms-of-use`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
